### ISSUE TITLE
Handle different combinations of package purity

### ISSUE THREAD

**Issue by chrisjbillington** [rpanderson/workflow-sandbox#17]
(I'm working on this, just documenting what I'm working on)

There are three types of Python packages that we have, each requiring slightly different build steps. The types of packages and build steps required are:

1. Pure Python packages (no compiled extensions) with no platform-/python-version-specific dependencies.
    * single sdist
    * single pure wheel
    * single `noarch` conda package

2. Pure Python packages, with platform/python-version-specific dependencies
    * single sdist
    * single pure wheel
    * `{pythons} × {win-32, win-64, linux-64, osx-64}` conda packages

3. Packages with compiled extensions:
    * single sdist
    * `{pythons} × {win-32, win-64, osx-64}` wheels compiled on the latest OS versions
    * `{pythons} × {linux-64}` wheels compiled using the `manylinux` docker image
    * `{pythons} × {win-32, win-64, linux-64, osx-64}` conda packages

I've done type 3. in [desktop-app](https://github.com/chrisjbillington/desktop-app), so the other variants are a simpler kind of it.

I'm going to test if we can define global hard-coded switches in workflows that say which jobs to run (I think we probably can with job-level `if` conditions based on workflow-level environment variables). 

If we can, then we can make a single workflow file differing between projects only in these switches (and I guess hard-coded repository names), containing all the steps even if they are not in use. Barring that we can just include the jobs in a repository that are actually in use, but verbatim rather than combining them where possible (e.g not combining the sdist and wheel jobs even for the case of pure packages), to ease keeping any changes in sync between repositories.

So the steps we'll need are:

- a. sdist
- b. pure wheel
- c. impure mac and windows wheels
- d. impure manylinux wheels
- e. single noarch conda package
- f. impure conda packages

Package type 1.  has a, b, e. Type 2 has a, b, f. Type 3 has a, c, d, f.

**Comment by chrisjbillington** [comment]
[No beans](https://github.community/t5/GitHub-Actions/jobs-lt-job-id-gt-if-does-not-work-with-env-secrets/td-p/38549) on job-level `if` conditionals using the workflow-level `env` context.

**Comment by chrisjbillington** [comment]
Ok, so since it's not possible to block out whole jobs and it's a lot of duplication to split into multiple jobs, I'll try to make it just 2 build jobs - one for manylinux and one for sdist, other wheels and conda, with the job matrix being the configuration you need to change for different 'purity classes'.

**Comment by philipstarkey** [comment]
Doesn't the last post in the linked thread say you can use the env context in if conditionals, just not secrets?

**Comment by rpanderson** [comment]
Thanks for documenting this, @chrisjbillington. And well done getting type 3 working.

> Ok, so since it's not possible to block out whole jobs

You mean using environment variables, per your earlier post? That's been my experience.

**Comment by chrisjbillington** [comment]
> Doesn't the last post in the linked thread say you can use the env context in if conditionals, just not secrets?

[This comment](https://github.community/t5/GitHub-Actions/jobs-lt-job-id-gt-if-does-not-work-with-env-secrets/m-p/48407/highlight/true#M7144) implies you cant use the env context in a job-level if. Though I tried it and got no luck.

**Comment by chrisjbillington** [comment]
This is done!
